openapi: 3.0.0
info:
  version: 1.0.0
  title: Zadanie 3
paths:
  /v1/upload:
    post:
      summary: Upload an image parts with etags
      tags:
        - Upload
      parameters:
        - in: header
          name: Authorization
          description: Bearer token for authentication
          required: true
          schema:
            type: string
      requestBody:
        description: Image parts upload with etags
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  part:
                    type: integer
                  etag:
                    type: string
                required:
                  - part
                  - etag
            example:
              - part: 1
                etag: a54357aff0632cce46d942af68356b38
              - part: 2
                etag: 0c78aef83f66abc1fa1e8477f296d394
              - part: 3
                etag: acbd18db4cc2f85cedef654fccc4a4d8
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  timestamp:
                    type: integer
                  source:
                    type: string
                  folder:
                    type: string
                  height:
                    type: integer
                  width:
                    type: integer
                  mime:
                    type: string
                  display:
                    type: object
                    properties:
                      thumbnail:
                        type: object
                        properties:
                          width:
                            type: integer
                          height:
                            type: integer
                          src:
                            type: string
                      preview:
                        type: object
                        properties:
                          width:
                            type: integer
                          height:
                            type: integer
                          src:
                            type: string
                      square:
                        type: object
                        properties:
                          width:
                            type: integer
                          height:
                            type: integer
                          src:
                            type: string
                      original:
                        type: object
                        properties:
                          width:
                            type: integer
                          height:
                            type: integer
                          src:
                            type: string
                  metadata:
                    type: object
                    properties:
                      gps:
                        type: string
                      datetime:
                        type: integer
                      name:
                        type: string
              example:
                id: 2058959
                timestamp: 1516354800
                source: instagram
                folder: null
                height: 1080
                width: 1080
                mime: image/jpeg
                display:
                  thumbnail:
                    width: 200
                    height: 200
                    src: https://printu.test/media/catalog/cache/vH72u0x7Y4uf0Tdd1j%252F34EFgAluLOcapxlHI0rcqWYDEZi8ph6XztIGW4VGE1cuYIyIE/image.jpg
                  preview:
                    width: 800
                    height: 800
                    src: https://printu.test/media/catalog/cache/vH72u0x7Y4uf0Tdd1j%252F34EFgAluLOcapxlHI0rcqWYDEZi8ph6XztIsI%252BRE60RFRtAsn/image.jpg
                  square:
                    width: 200
                    height: 200
                    src: https://printu.test/media/catalog/cache/vH72u0x7Y4uf0Tdd1j%252F34EFgAluLOcapxlHI0rcqWYDEZi8ph6XztIsI%252BRE60RFRtAsn/image.jpg
                  original:
                    width: 1080
                    height: 1080
                    src: https://dev-printu-net.s3.eu-central-1.amazonaws.com/photobook/12/7/0/2058959.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAILKHTK5ZOAVQB23Q%2F20180209%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20180209T092316Z&X-Amz-SignedHeaders=host&X-Amz-Expires=518400&X-Amz-Signature=cc95d836e2235992e1948add1bc8f5cdb35d39dc974f8cfa23efd9895db32d38
                metadata:
                  gps: "52/1, 15/1, 272/100 N 21/1, 1/1, 5851/100 E"
                  datetime: 1516354800
                  name: "IMG_9171.JPG"
        '4XX':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: integer
                  userMessage:
                    type: string
                  devMessage:
                    type: string
                  more:
                    type: string
                  applicationCode:
                    type: string
              example:
                errorCode: 400
                userMessage: "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed."
                devMessage: "Check the client_id parameter."
                more: ""
                applicationCode: "X1234"
        '5XX':
          description: Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: integer
                  userMessage:
                    type: string
                  devMessage:
                    type: string
                  more:
                    type: string
                  applicationCode:
                    type: string
              example:
                errorCode: 500
                userMessage: "Internal Server Error"
                devMessage: "An unexpected condition was encountered."
                more: ""
                applicationCode: "X1234"